Zero Changes Implemented
BurkusCat/r6-operator-counters pull request #188
Opened 2020-11-22 22:31 UTC by bazexe

Implemented the counter changes for Zero.

2020-11-23 21:43 UTC, BurkusCat requested changes
Looks really good @bazexe ! There are only a few small changes needed :)

2020-11-23 21:43 UTC, BurkusCat commented on src/main/create-operator-json/operators/wamai.js
> +wamai.addCounterNode(operatorId.zero, counterType.hard, "Wamai's MAG-NET System will grab Zero's cameras out of the air and destroy them");
Fullstop/period needed at the end

2020-11-23 21:43 UTC, BurkusCat commented on src/main/create-operator-json/operators/zero.js
> +zero.addCounterNode(operatorId.mira, counterType.hard, "Mira's black mirrors can be destroyed by Zero's zap.");
Potentially change all of these to "...by Zero's Argus camera zap."?

2020-11-23 21:43 UTC, BurkusCat commented on src/main/scripts/imageLocation.js
> +	    'Zero': 'img/' + fileFormat + '/zero.' + fileFormat,
I think the indentation needs changed slightly for this

2020-11-23 21:46 UTC, BurkusCat commented
Quick question, did you test these changes out @bazexe ? I think the first step of this guide may need to be run as well: https://github.com/BurkusCat/r6-operator-counters/wiki/How-to%3A-Add-a-new-operator Otherwise, I wouldn't expect Zero's icon to show up.

2020-11-23 22:31 UTC, bazexe commented
Yes I tested them. I checked the R6operator Icons and Zero had already been
added to the icons. I tested it on my ubuntu virtual machine and was able
to get the icon to show up along with the relationships. I will implement
the changes you said as well.

Regards,
Arbaaz Syed


On Mon, Nov 23, 2020 at 3:46 PM Ronan <notifications@github.com> wrote:

> Quick question, did you test these changes out @bazexe
> <https://github.com/bazexe> ? I think the first step of this guide may
> need to be run as well:
> https://github.com/BurkusCat/r6-operator-counters/wiki/How-to%3A-Add-a-new-operator
> Otherwise, I wouldn't expect Zero's icon to show up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/BurkusCat/r6-operator-counters/pull/188#issuecomment-732444892>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQZYLXYAXPOVUWVDHCANVHLSRLJ2RANCNFSM4T6YTUEA>
> .
>

2021-02-28 16:53 UTC, BurkusCat commented
Hi @bazexe, how's it going? I just wanted to check if you were still interested in making these changes :) No pressure if you don't want to!

Hope you are keeping well!
- Burkus

2022-04-27 16:18 UTC, BurkusCat commented
Thank you @bazexe for your contribution! @Trufflegator took over the changes you made here and made the finishing touches in this PR: #205

Hope you are well!

2022-04-27 16:18 UTC, closed without merging